In [1]:
# ================================
# 1. SETUP
# ================================

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import pandas as pd
import json
import time

options = Options()
options.add_argument("--start-maximized")

driver = webdriver.Chrome(options=options)

# Página base (clave para evitar bloqueo)
driver.get("https://resultadoelectoral.onpe.gob.pe/main/presidenciales")
time.sleep(5)

# ================================
# 2. REGIONES
# ================================

departamentos = [
    ("010000","AMAZONAS"),
    ("020000","ANCASH"),
    ("030000","APURIMAC"),
    ("040000","AREQUIPA"),
    ("050000","AYACUCHO"),
    ("060000","CAJAMARCA"),
    ("240000","CALLAO"),
    ("070000","CUSCO"),
    ("080000","HUANCAVELICA"),
    ("090000","HUANUCO"),
    ("100000","ICA"),
    ("110000","JUNIN"),
    ("120000","LA LIBERTAD"),
    ("130000","LAMBAYEQUE"),
    ("140000","LIMA"),
    ("150000","LORETO"),
    ("160000","MADRE DE DIOS"),
    ("170000","MOQUEGUA"),
    ("180000","PASCO"),
    ("190000","PIURA"),
    ("200000","PUNO"),
    ("210000","SAN MARTIN"),
    ("220000","TACNA"),
    ("230000","TUMBES"),
    ("250000","UCAYALI")
]

# ================================
# 3. EXTRAER PROVINCIAS
# ================================

provincias = []

for ubigeo_dep, nombre_dep in departamentos:
    
    url = f"https://resultadoelectoral.onpe.gob.pe/presentacion-backend/ubigeos/provincias?idEleccion=10&idAmbitoGeografico=1&idUbigeoDepartamento={ubigeo_dep}"
    
    print(f"Provincias {nombre_dep}...")

    driver.get(url)
    time.sleep(2)

    texto = driver.find_element("tag name", "body").text

    try:
        data = json.loads(texto)["data"]

        for p in data:
            provincias.append({
                "departamento": nombre_dep,
                "ubigeo_dep": ubigeo_dep,
                "ubigeo_prov": p["ubigeo"],
                "provincia": p["nombre"]
            })

    except Exception as e:
        print(f"❌ Error provincias {nombre_dep}: {e}")

df_provincias = pd.DataFrame(provincias)

print("✅ Provincias cargadas")

# ================================
# 4. VOTOS POR PROVINCIA
# ================================

votos = []

for i, row in df_provincias.iterrows():

    url = f"https://resultadoelectoral.onpe.gob.pe/presentacion-backend/eleccion-presidencial/participantes-ubicacion-geografica-nombre?tipoFiltro=ubigeo_nivel_02&idAmbitoGeografico=1&ubigeoNivel1={row['ubigeo_dep']}&ubigeoNivel2={row['ubigeo_prov']}&idEleccion=10"

    print(f"Votos {row['provincia']} ({row['departamento']})")

    driver.get(url)
    time.sleep(2)

    texto = driver.find_element("tag name", "body").text

    try:
        data = json.loads(texto)["data"]

        for fila in data:
            votos.append({
                "departamento": row["departamento"],
                "provincia": row["provincia"],
                "candidato": fila["nombreCandidato"],
                "partido": fila["nombreAgrupacionPolitica"],
                "votos": fila.get("totalVotosValidos", 0)
            })

    except Exception as e:
        print(f"❌ Error votos {row['provincia']}: {e}")

df_votos = pd.DataFrame(votos)

print("✅ Votos cargados")

# ================================
# 5. ACTAS POR PROVINCIA
# ================================

actas = []

for i, row in df_provincias.iterrows():

    url = f"https://resultadoelectoral.onpe.gob.pe/presentacion-backend/resumen-general/totales?idAmbitoGeografico=1&idEleccion=10&tipoFiltro=ubigeo_nivel_02&idUbigeoDepartamento={row['ubigeo_dep']}&idUbigeoProvincia={row['ubigeo_prov']}"

    print(f"Actas {row['provincia']} ({row['departamento']})")

    driver.get(url)
    time.sleep(2)

    texto = driver.find_element("tag name", "body").text

    try:
        data = json.loads(texto)["data"]

        actas.append({
            "departamento": row["departamento"],
            "provincia": row["provincia"],
            "actas_total": data["totalActas"],
            "actas_procesadas": data["contabilizadas"],
            "avance_pct": data["actasContabilizadas"],
            "votos_validos_prov": data["totalVotosValidos"]
        })

    except Exception as e:
        print(f"❌ Error actas {row['provincia']}: {e}")

df_actas = pd.DataFrame(actas)

print("✅ Actas cargadas")

# ================================
# 6. MERGE FINAL
# ================================

df_final = df_votos.merge(
    df_actas,
    on=["departamento", "provincia"]
)

# ================================
# 7. EXPORTAR
# ================================

df_final.to_csv("resultado_provincial_completo.csv", index=False)

print("\n🔥 LISTO")
print("Archivo generado: resultado_provincial_completo.csv")

# ================================
# 8. PREVIEW
# ================================

df_final.head()

Provincias AMAZONAS...
Provincias ANCASH...
Provincias APURIMAC...
Provincias AREQUIPA...
Provincias AYACUCHO...
Provincias CAJAMARCA...
Provincias CALLAO...
Provincias CUSCO...
Provincias HUANCAVELICA...
Provincias HUANUCO...
Provincias ICA...
Provincias JUNIN...
Provincias LA LIBERTAD...
Provincias LAMBAYEQUE...
Provincias LIMA...
Provincias LORETO...
Provincias MADRE DE DIOS...
Provincias MOQUEGUA...
Provincias PASCO...
Provincias PIURA...
Provincias PUNO...
Provincias SAN MARTIN...
Provincias TACNA...
Provincias TUMBES...
Provincias UCAYALI...
✅ Provincias cargadas
Votos BAGUA (AMAZONAS)
Votos BONGARÁ (AMAZONAS)
Votos CHACHAPOYAS (AMAZONAS)
Votos CONDORCANQUI (AMAZONAS)
Votos LUYA (AMAZONAS)
Votos RODRÍGUEZ DE MENDOZA (AMAZONAS)
Votos UTCUBAMBA (AMAZONAS)
Votos AIJA (ANCASH)
Votos ANTONIO RAIMONDI (ANCASH)
Votos ASUNCIÓN (ANCASH)
Votos BOLOGNESI (ANCASH)
Votos CARHUAZ (ANCASH)
Votos CARLOS FERMÍN FITZCARRALD (ANCASH)
Votos CASMA (ANCASH)
Votos CORONGO (ANCASH)
Votos HUARAZ (ANCASH)
Votos HUARI (ANCASH)
Votos HUARMEY (ANCASH)
Votos HUAYLAS (ANCASH)
Votos MARISCAL LUZURIAGA (ANCASH)
Votos OCROS (ANCASH)
Votos PALLASCA (ANCASH)
Votos POMABAMBA (ANCASH)
Votos RECUAY (ANCASH)
Votos SANTA (ANCASH)
Votos SIHUAS (ANCASH)
Votos YUNGAY (ANCASH)
Votos ABANCAY (APURIMAC)
Votos ANDAHUAYLAS (APURIMAC)
Votos ANTABAMBA (APURIMAC)
Votos AYMARAES (APURIMAC)
Votos CHINCHEROS (APURIMAC)
Votos COTABAMBAS (APURIMAC)
Votos GRAU (APURIMAC)
Votos AREQUIPA (AREQUIPA)
Votos CAMANÁ (AREQUIPA)
Votos CARAVELÍ (AREQUIPA)
Votos CASTILLA (AREQUIPA)
Votos CAYLLOMA (AREQUIPA)
Votos CONDESUYOS (AREQUIPA)
Votos ISLAY (AREQUIPA)
Votos LA UNIÓN (AREQUIPA)
Votos CANGALLO (AYACUCHO)
Votos HUAMANGA (AYACUCHO)
Votos HUANCA SANCOS (AYACUCHO)
Votos HUANTA (AYACUCHO)
Votos LA MAR (AYACUCHO)
Votos LUCANAS (AYACUCHO)
Votos PARINACOCHAS (AYACUCHO)
Votos PÁUCAR DEL SARA SARA (AYACUCHO)
Votos SUCRE (AYACUCHO)
Votos VÍCTOR FAJARDO (AYACUCHO)
Votos VILCAS HUAMÁN (AYACUCHO)
Votos CAJABAMBA (CAJAMARCA)
Votos CAJAMARCA (CAJAMARCA)
Votos CELENDÍN (CAJAMARCA)
Votos CHOTA (CAJAMARCA)
Votos CONTUMAZA (CAJAMARCA)
Votos CUTERVO (CAJAMARCA)
Votos HUALGAYOC (CAJAMARCA)
Votos JAÉN (CAJAMARCA)
Votos SAN IGNACIO (CAJAMARCA)
Votos SAN MARCOS (CAJAMARCA)
Votos SAN MIGUEL (CAJAMARCA)
Votos SAN PABLO (CAJAMARCA)
Votos SANTA CRUZ (CAJAMARCA)
Votos CALLAO (CALLAO)
Votos ACOMAYO (CUSCO)
Votos ANTA (CUSCO)
Votos CALCA (CUSCO)
Votos CANAS (CUSCO)
Votos CANCHIS (CUSCO)
Votos CHUMBIVILCAS (CUSCO)
Votos CUSCO (CUSCO)
Votos ESPINAR (CUSCO)
Votos LA CONVENCIÓN (CUSCO)
Votos PARURO (CUSCO)
Votos PAUCARTAMBO (CUSCO)
Votos QUISPICANCHI (CUSCO)
Votos URUBAMBA (CUSCO)
Votos ACOBAMBA (HUANCAVELICA)
Votos ANGARAES (HUANCAVELICA)
Votos CASTROVIRREYNA (HUANCAVELICA)
Votos CHURCAMPA (HUANCAVELICA)
Votos HUANCAVELICA (HUANCAVELICA)
Votos HUAYTARA (HUANCAVELICA)
Votos TAYACAJA (HUANCAVELICA)
Votos AMBO (HUANUCO)
Votos DOS DE MAYO (HUANUCO)
Votos HUACAYBAMBA (HUANUCO)
Votos HUAMALIES (HUANUCO)
Votos HUÁNUCO (HUANUCO)
Votos LAURICOCHA (HUANUCO)
Votos LEONCIO PRADO (HUANUCO)
Votos MARAÑÓN (HUANUCO)
Votos PACHITEA (HUANUCO)
Votos PUERTO INCA (HUANUCO)
Votos YAROWILCA (HUANUCO)
Votos CHINCHA (ICA)
Votos ICA (ICA)
Votos NASCA (ICA)
Votos PALPA (ICA)
Votos PISCO (ICA)
Votos CHANCHAMAYO (JUNIN)
Votos CHUPACA (JUNIN)
Votos CONCEPCIÓN (JUNIN)
Votos HUANCAYO (JUNIN)
Votos JAUJA (JUNIN)
Votos JUNÍN (JUNIN)
Votos SATIPO (JUNIN)
Votos TARMA (JUNIN)
Votos YAULI (JUNIN)
Votos ASCOPE (LA LIBERTAD)
Votos BOLÍVAR (LA LIBERTAD)
Votos CHEPÉN (LA LIBERTAD)
Votos GRAN CHIMÚ (LA LIBERTAD)
Votos JULCÁN (LA LIBERTAD)
Votos OTUZCO (LA LIBERTAD)
Votos PACASMAYO (LA LIBERTAD)
Votos PATAZ (LA LIBERTAD)
Votos SÁNCHEZ CARRIÓN (LA LIBERTAD)
Votos SANTIAGO DE CHUCO (LA LIBERTAD)
Votos TRUJILLO (LA LIBERTAD)
Votos VIRÚ (LA LIBERTAD)
Votos CHICLAYO (LAMBAYEQUE)
Votos FERREÑAFE (LAMBAYEQUE)
Votos LAMBAYEQUE (LAMBAYEQUE)
Votos BARRANCA (LIMA)
Votos CAJATAMBO (LIMA)
Votos CANTA (LIMA)
Votos CAÑETE (LIMA)
Votos HUARAL (LIMA)
Votos HUAROCHIRÍ (LIMA)
Votos HUAURA (LIMA)
Votos LIMA (LIMA)
Votos OYÓN (LIMA)
Votos YAUYOS (LIMA)
Votos ALTO AMAZONAS (LORETO)
Votos DATEM DEL MARAÑÓN (LORETO)
Votos LORETO (LORETO)
Votos MARISCAL RAMÓN CASTILLA (LORETO)
Votos MAYNAS (LORETO)
Votos PUTUMAYO (LORETO)
Votos REQUENA (LORETO)
Votos UCAYALI (LORETO)
Votos MANÚ (MADRE DE DIOS)
Votos TAHUAMANÚ (MADRE DE DIOS)
Votos TAMBOPATA (MADRE DE DIOS)
Votos GENERAL SÁNCHEZ CERRO (MOQUEGUA)
Votos ILO (MOQUEGUA)
Votos MARISCAL NIETO (MOQUEGUA)
Votos DANIEL ALCIDES CARRIÓN (PASCO)
Votos OXAPAMPA (PASCO)
Votos PASCO (PASCO)
Votos AYABACA (PIURA)
Votos HUANCABAMBA (PIURA)
Votos MORROPÓN (PIURA)
Votos PAITA (PIURA)
Votos PIURA (PIURA)
Votos SECHURA (PIURA)
Votos SULLANA (PIURA)
Votos TALARA (PIURA)
Votos AZÁNGARO (PUNO)
Votos CARABAYA (PUNO)
Votos CHUCUITO (PUNO)
Votos EL COLLAO (PUNO)
Votos HUANCANÉ (PUNO)
Votos LAMPA (PUNO)
Votos MELGAR (PUNO)
Votos MOHO (PUNO)
Votos PUNO (PUNO)
Votos SAN ANTONIO DE PUTINA (PUNO)
Votos SANDIA (PUNO)
Votos SAN ROMÁN (PUNO)
Votos YUNGUYO (PUNO)
Votos BELLAVISTA (SAN MARTIN)
Votos EL DORADO (SAN MARTIN)
Votos HUALLAGA (SAN MARTIN)
Votos LAMAS (SAN MARTIN)
Votos MARISCAL CÁCERES (SAN MARTIN)
Votos MOYOBAMBA (SAN MARTIN)
Votos PICOTA (SAN MARTIN)
Votos RIOJA (SAN MARTIN)
Votos SAN MARTÍN (SAN MARTIN)
Votos TOCACHE (SAN MARTIN)
Votos CANDARAVE (TACNA)
Votos JORGE BASADRE (TACNA)
Votos TACNA (TACNA)
Votos TARATA (TACNA)
Votos CONTRALMIRANTE VILLAR (TUMBES)
Votos TUMBES (TUMBES)
Votos ZARUMILLA (TUMBES)
Votos ATALAYA (UCAYALI)
Votos CORONEL PORTILLO (UCAYALI)
Votos PADRE ABAD (UCAYALI)
Votos PURÚS (UCAYALI)
✅ Votos cargados
Actas BAGUA (AMAZONAS)
Actas BONGARÁ (AMAZONAS)
Actas CHACHAPOYAS (AMAZONAS)
Actas CONDORCANQUI (AMAZONAS)
Actas LUYA (AMAZONAS)
Actas RODRÍGUEZ DE MENDOZA (AMAZONAS)
Actas UTCUBAMBA (AMAZONAS)
Actas AIJA (ANCASH)
Actas ANTONIO RAIMONDI (ANCASH)
Actas ASUNCIÓN (ANCASH)
Actas BOLOGNESI (ANCASH)
Actas CARHUAZ (ANCASH)
Actas CARLOS FERMÍN FITZCARRALD (ANCASH)
Actas CASMA (ANCASH)
Actas CORONGO (ANCASH)
Actas HUARAZ (ANCASH)
Actas HUARI (ANCASH)
Actas HUARMEY (ANCASH)
Actas HUAYLAS (ANCASH)
Actas MARISCAL LUZURIAGA (ANCASH)
Actas OCROS (ANCASH)
Actas PALLASCA (ANCASH)
Actas POMABAMBA (ANCASH)
Actas RECUAY (ANCASH)
Actas SANTA (ANCASH)
Actas SIHUAS (ANCASH)
Actas YUNGAY (ANCASH)
Actas ABANCAY (APURIMAC)
Actas ANDAHUAYLAS (APURIMAC)
Actas ANTABAMBA (APURIMAC)
Actas AYMARAES (APURIMAC)
Actas CHINCHEROS (APURIMAC)
Actas COTABAMBAS (APURIMAC)
Actas GRAU (APURIMAC)
Actas AREQUIPA (AREQUIPA)
Actas CAMANÁ (AREQUIPA)
Actas CARAVELÍ (AREQUIPA)
Actas CASTILLA (AREQUIPA)
Actas CAYLLOMA (AREQUIPA)
Actas CONDESUYOS (AREQUIPA)
Actas ISLAY (AREQUIPA)
Actas LA UNIÓN (AREQUIPA)
Actas CANGALLO (AYACUCHO)
Actas HUAMANGA (AYACUCHO)
Actas HUANCA SANCOS (AYACUCHO)
Actas HUANTA (AYACUCHO)
Actas LA MAR (AYACUCHO)
Actas LUCANAS (AYACUCHO)
Actas PARINACOCHAS (AYACUCHO)
Actas PÁUCAR DEL SARA SARA (AYACUCHO)
Actas SUCRE (AYACUCHO)
Actas VÍCTOR FAJARDO (AYACUCHO)
Actas VILCAS HUAMÁN (AYACUCHO)
Actas CAJABAMBA (CAJAMARCA)
Actas CAJAMARCA (CAJAMARCA)
Actas CELENDÍN (CAJAMARCA)
Actas CHOTA (CAJAMARCA)
Actas CONTUMAZA (CAJAMARCA)
Actas CUTERVO (CAJAMARCA)
Actas HUALGAYOC (CAJAMARCA)
Actas JAÉN (CAJAMARCA)
Actas SAN IGNACIO (CAJAMARCA)
Actas SAN MARCOS (CAJAMARCA)
Actas SAN MIGUEL (CAJAMARCA)
Actas SAN PABLO (CAJAMARCA)
Actas SANTA CRUZ (CAJAMARCA)
Actas CALLAO (CALLAO)
Actas ACOMAYO (CUSCO)
Actas ANTA (CUSCO)
Actas CALCA (CUSCO)
Actas CANAS (CUSCO)
Actas CANCHIS (CUSCO)
Actas CHUMBIVILCAS (CUSCO)
Actas CUSCO (CUSCO)
Actas ESPINAR (CUSCO)
Actas LA CONVENCIÓN (CUSCO)
Actas PARURO (CUSCO)
Actas PAUCARTAMBO (CUSCO)
Actas QUISPICANCHI (CUSCO)
Actas URUBAMBA (CUSCO)
Actas ACOBAMBA (HUANCAVELICA)
Actas ANGARAES (HUANCAVELICA)
Actas CASTROVIRREYNA (HUANCAVELICA)
Actas CHURCAMPA (HUANCAVELICA)
Actas HUANCAVELICA (HUANCAVELICA)
Actas HUAYTARA (HUANCAVELICA)
Actas TAYACAJA (HUANCAVELICA)
Actas AMBO (HUANUCO)
Actas DOS DE MAYO (HUANUCO)
Actas HUACAYBAMBA (HUANUCO)
Actas HUAMALIES (HUANUCO)
Actas HUÁNUCO (HUANUCO)
Actas LAURICOCHA (HUANUCO)
Actas LEONCIO PRADO (HUANUCO)
Actas MARAÑÓN (HUANUCO)
Actas PACHITEA (HUANUCO)
Actas PUERTO INCA (HUANUCO)
Actas YAROWILCA (HUANUCO)
Actas CHINCHA (ICA)
Actas ICA (ICA)
Actas NASCA (ICA)
Actas PALPA (ICA)
Actas PISCO (ICA)
Actas CHANCHAMAYO (JUNIN)
Actas CHUPACA (JUNIN)
Actas CONCEPCIÓN (JUNIN)
Actas HUANCAYO (JUNIN)
Actas JAUJA (JUNIN)
Actas JUNÍN (JUNIN)
Actas SATIPO (JUNIN)
Actas TARMA (JUNIN)
Actas YAULI (JUNIN)
Actas ASCOPE (LA LIBERTAD)
Actas BOLÍVAR (LA LIBERTAD)
Actas CHEPÉN (LA LIBERTAD)
Actas GRAN CHIMÚ (LA LIBERTAD)
Actas JULCÁN (LA LIBERTAD)
Actas OTUZCO (LA LIBERTAD)
Actas PACASMAYO (LA LIBERTAD)
Actas PATAZ (LA LIBERTAD)
Actas SÁNCHEZ CARRIÓN (LA LIBERTAD)
Actas SANTIAGO DE CHUCO (LA LIBERTAD)
Actas TRUJILLO (LA LIBERTAD)
Actas VIRÚ (LA LIBERTAD)
Actas CHICLAYO (LAMBAYEQUE)
Actas FERREÑAFE (LAMBAYEQUE)
Actas LAMBAYEQUE (LAMBAYEQUE)
Actas BARRANCA (LIMA)
Actas CAJATAMBO (LIMA)
Actas CANTA (LIMA)
Actas CAÑETE (LIMA)
Actas HUARAL (LIMA)
Actas HUAROCHIRÍ (LIMA)
Actas HUAURA (LIMA)
Actas LIMA (LIMA)
Actas OYÓN (LIMA)
Actas YAUYOS (LIMA)
Actas ALTO AMAZONAS (LORETO)
Actas DATEM DEL MARAÑÓN (LORETO)
Actas LORETO (LORETO)
Actas MARISCAL RAMÓN CASTILLA (LORETO)
Actas MAYNAS (LORETO)
Actas PUTUMAYO (LORETO)
Actas REQUENA (LORETO)
Actas UCAYALI (LORETO)
Actas MANÚ (MADRE DE DIOS)
Actas TAHUAMANÚ (MADRE DE DIOS)
Actas TAMBOPATA (MADRE DE DIOS)
Actas GENERAL SÁNCHEZ CERRO (MOQUEGUA)
Actas ILO (MOQUEGUA)
Actas MARISCAL NIETO (MOQUEGUA)
Actas DANIEL ALCIDES CARRIÓN (PASCO)
Actas OXAPAMPA (PASCO)
Actas PASCO (PASCO)
Actas AYABACA (PIURA)
Actas HUANCABAMBA (PIURA)
Actas MORROPÓN (PIURA)
Actas PAITA (PIURA)
Actas PIURA (PIURA)
Actas SECHURA (PIURA)
Actas SULLANA (PIURA)
Actas TALARA (PIURA)
Actas AZÁNGARO (PUNO)
Actas CARABAYA (PUNO)
Actas CHUCUITO (PUNO)
Actas EL COLLAO (PUNO)
Actas HUANCANÉ (PUNO)
Actas LAMPA (PUNO)
Actas MELGAR (PUNO)
Actas MOHO (PUNO)
Actas PUNO (PUNO)
Actas SAN ANTONIO DE PUTINA (PUNO)
Actas SANDIA (PUNO)
Actas SAN ROMÁN (PUNO)
Actas YUNGUYO (PUNO)
Actas BELLAVISTA (SAN MARTIN)
Actas EL DORADO (SAN MARTIN)
Actas HUALLAGA (SAN MARTIN)
Actas LAMAS (SAN MARTIN)
Actas MARISCAL CÁCERES (SAN MARTIN)
Actas MOYOBAMBA (SAN MARTIN)
Actas PICOTA (SAN MARTIN)
Actas RIOJA (SAN MARTIN)
Actas SAN MARTÍN (SAN MARTIN)
Actas TOCACHE (SAN MARTIN)
Actas CANDARAVE (TACNA)
Actas JORGE BASADRE (TACNA)
Actas TACNA (TACNA)
Actas TARATA (TACNA)
Actas CONTRALMIRANTE VILLAR (TUMBES)
Actas TUMBES (TUMBES)
Actas ZARUMILLA (TUMBES)
Actas ATALAYA (UCAYALI)
Actas CORONEL PORTILLO (UCAYALI)
Actas PADRE ABAD (UCAYALI)
Actas PURÚS (UCAYALI)
✅ Actas cargadas

🔥 LISTO
Archivo generado: resultado_provincial_completo.csv

,departamento,provincia,candidato,partido,votos,actas_total,actas_procesadas,avance_pct,votos_validos_prov
0,AMAZONAS,BAGUA,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,7988,250,151,60.4,22446
1,AMAZONAS,BAGUA,,VOTOS EN BLANCO,4609,250,151,60.4,22446
2,AMAZONAS,BAGUA,KEIKO SOFIA FUJIMORI HIGUCHI,FUERZA POPULAR,4179,250,151,60.4,22446
3,AMAZONAS,BAGUA,RICARDO PABLO BELMONT CASSINELLI,PARTIDO CÍVICO OBRAS,2286,250,151,60.4,22446
4,AMAZONAS,BAGUA,,VOTOS NULOS,1926,250,151,60.4,22446

In [2]:
# ================================
# 1. LIMPIEZA BÁSICA
# ================================

import numpy as np

df = df_final.copy()

# Evitar divisiones por 0
df["avance_pct"] = df["avance_pct"].replace(0, np.nan)

# ================================
# 2. EXTRAPOLACIÓN PROVINCIAL
# ================================

df["factor_expansion"] = 100 / df["avance_pct"]

df["votos_estimados"] = df["votos"] * df["factor_expansion"]

# ================================
# 3. VOTOS RESTANTES (insight clave)
# ================================

df["votos_restantes"] = df["votos_estimados"] - df["votos"]

# ================================
# 4. AGREGAR A NIVEL NACIONAL
# ================================

df_nacional = (
    df
    .groupby(["candidato", "partido"], as_index=False)
    .agg({
        "votos": "sum",
        "votos_estimados": "sum",
        "votos_restantes": "sum"
    })
)

# ================================
# 5. IDENTIFICAR NO VÁLIDOS
# ================================

no_validos = ["VOTOS EN BLANCO", "VOTOS NULOS"]

# Total votos válidos estimados
total_validos = df_nacional[
    ~df_nacional["partido"].isin(no_validos)
]["votos_estimados"].sum()

# ================================
# 6. % VOTOS VÁLIDOS
# ================================

df_nacional["pct_votos_validos"] = df_nacional.apply(
    lambda row: row["votos_estimados"] / total_validos * 100
    if row["partido"] not in no_validos else None,
    axis=1
)

# ================================
# 7. ORDENAR
# ================================

df_nacional = df_nacional.sort_values(
    by="votos_estimados",
    ascending=False
)

# ================================
# 8. TOP 20
# ================================

top20 = df_nacional.head(20)

print("\n🔥 TOP 20 NACIONAL (EXTRAPOLACIÓN PROVINCIAL)\n")
print(top20)

# ================================
# 9. EXPORTAR
# ================================

top20.to_csv("top20_nacional_provincial.csv", index=False)

print("\n✅ Archivo generado: top20_nacional_provincial.csv")

🔥 TOP 20 NACIONAL (EXTRAPOLACIÓN PROVINCIAL)

                               candidato  \
18          KEIKO SOFIA FUJIMORI HIGUCHI
0
31      ROBERTO HELBERT SANCHEZ PALOMINO
27  RAFAEL BERNARDO LÓPEZ ALIAGA CAZORLA
15                JORGE NIETO MONTESINOS
29      RICARDO PABLO BELMONT CASSINELLI
8          CARLOS GONSALO ALVAREZ LOAYZA
24         PABLO ALFONSO LOPEZ CHAU NAVA
1
20             MARIA SOLEDAD PEREZ TELLO
3    ALFONSO CARLOS ESPA Y GARCES-ALVEAR
19            LUIS FERNANDO OLIVERA VEGA
17                 JOSE LEON LUNA GALVEZ
37                 YONHY LESCANO ANCIETA
9                    CESAR ACUÑA PERALTA
26        PITTER ENRIQUE VALDERRAMA PEÑA
13         GEORGE PATRICK FORSYTH SOMMER
21        MARIO ENRIQUE VIZCARRA CORNEJO
14              HERBERT CALLER GUTIERREZ
32       RONALD DARWIN ATENCIO SOTOMAYOR

                                              partido    votos  \
18                                     FUERZA POPULAR  2265194
0                                     VOTOS EN BLANCO  1720929
31                                 JUNTOS POR EL PERÚ  1397614
27                                 RENOVACIÓN POPULAR  1693988
15                          PARTIDO DEL BUEN GOBIERNO  1578957
29                               PARTIDO CÍVICO OBRAS  1347196
8                             PARTIDO PAÍS PARA TODOS  1087101
24                                  AHORA NACIÓN - AN  1016671
1                                         VOTOS NULOS   762529
20  PRIMERO LA GENTE – COMUNIDAD, ECOLOGÍA, LIBERT...   487374
3                                      PARTIDO SICREO   478029
19                PARTIDO FRENTE DE LA ESPERANZA 2021   255200
17                                       PODEMOS PERÚ   198164
37               PARTIDO POLÍTICO COOPERACIÓN POPULAR   174841
9                            ALIANZA PARA EL PROGRESO   142731
26                            PARTIDO APRISTA PERUANO   128195
13                     PARTIDO DEMOCRÁTICO SOMOS PERÚ   118118
21                      PARTIDO POLÍTICO PERÚ PRIMERO   112226
14                        PARTIDO PATRIÓTICO DEL PERÚ   113676
32                       ALIANZA ELECTORAL VENCEREMOS   106309

    votos_estimados  votos_restantes  pct_votos_validos
18     2.846569e+06    581375.053824          17.259575
0      2.282754e+06    561825.151031                NaN
31     1.963043e+06    565428.571297          11.902497
27     1.941524e+06    247535.837100          11.772023
15     1.821020e+06    242063.012549          11.041373
29     1.654721e+06    307525.138830          10.033055
8      1.301241e+06    214140.271651           7.889804
24     1.214364e+06    197692.571969           7.363039
1      9.897077e+05    227178.684121                NaN
20     5.682816e+05     80907.637327           3.445657
3      5.629180e+05     84889.043178           3.413136
19     3.044536e+05     49253.598094           1.845991
17     2.623724e+05     64208.412714           1.590840
37     2.121749e+05     37333.899936           1.286478
9      1.868849e+05     44153.919745           1.133138
26     1.580790e+05     29884.002849           0.958479
13     1.556331e+05     37515.136976           0.943649
21     1.454180e+05     33191.975780           0.881711
14     1.436473e+05     29971.287187           0.870975
32     1.429203e+05     36611.325214           0.866567

✅ Archivo generado: top20_nacional_provincial.csv

In [3]:
df_sanchez = df[df["candidato"] == "ROBERTO HELBERT SANCHEZ PALOMINO"]

df_sanchez.sort_values("votos_restantes", ascending=False).head(20)

,departamento,provincia,candidato,partido,votos,actas_total,actas_procesadas,avance_pct,votos_validos_prov,factor_expansion,votos_estimados,votos_restantes
2090,CAJAMARCA,CELENDÍN,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,187,270,2,0.741,260,134.952767,25236.167341,25049.167341
5890,PIURA,HUANCABAMBA,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,2713,356,43,12.079,5136,8.278831,22460.468582,19747.468582
2128,CAJAMARCA,CHOTA,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,21273,465,250,53.763,40442,1.860015,39568.104458,18295.104458
2318,CAJAMARCA,SAN IGNACIO,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,17079,408,203,49.755,29915,2.009848,34326.198372,17247.198372
2052,CAJAMARCA,CAJAMARCA,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,27084,1021,629,61.606,117743,1.623219,43963.250333,16879.250333
5852,PIURA,AYABACA,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,4619,385,86,22.338,8559,4.476677,20677.768824,16058.768824
4144,JUNIN,SATIPO,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,116,545,4,0.734,473,136.239782,15803.814714,15687.814714
6992,SAN MARTIN,TOCACHE,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,242,233,4,1.717,594,58.241118,14094.350612,13852.350612
5102,LIMA,LIMA,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,140340,26368,24031,91.137,5077950,1.097249,153987.952204,13647.952204
2850,CUSCO,LA CONVENCIÓN,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,10576,632,285,45.095,42084,2.217541,23452.710944,12876.710944
6384,PUNO,MELGAR,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,632,202,10,4.950,1517,20.202020,12767.676768,12135.676768
2280,CAJAMARCA,JAÉN,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,20943,607,388,63.921,65940,1.564431,32763.880415,11820.880415
2736,CUSCO,CHUMBIVILCAS,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,3571,236,60,25.424,8073,3.933291,14045.783512,10474.783512
3610,HUANUCO,PACHITEA,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,2623,166,34,20.482,4428,4.882336,12806.366566,10183.366566
3268,HUANCAVELICA,TAYACAJA,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,11875,311,171,54.984,25223,1.818711,21597.191910,9722.191910
1748,AYACUCHO,LA MAR,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,3827,228,66,28.947,9208,3.454589,13220.713718,9393.713718
3879,ICA,PISCO,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,1889,426,72,16.901,14122,5.916810,11176.853441,9287.853441
2242,CAJAMARCA,HUALGAYOC,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,18027,264,175,66.288,27133,1.508569,27194.967415,9167.967415
7372,UCAYALI,PADRE ABAD,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,947,220,21,9.545,3196,10.476689,9921.424830,8974.424830
6194,PUNO,CARABAYA,ROBERTO HELBERT SANCHEZ PALOMINO,JUNTOS POR EL PERÚ,2387,190,43,22.632,6161,4.418522,10547.013079,8160.013079

In [4]:
df["avance_pct"].describe()

count    7296.000000
mean       69.131328
std        28.645066
min         0.734000
25%        55.653000
50%        80.358500
75%        92.628000
max       100.000000
Name: avance_pct, dtype: float64

In [5]:
df[df["avance_pct"] < 30].groupby("candidato")["votos"].sum().sort_values(ascending=False)

candidato
ROBERTO HELBERT SANCHEZ PALOMINO            33613
                                            31721
KEIKO SOFIA FUJIMORI HIGUCHI                16475
RICARDO PABLO BELMONT CASSINELLI            11481
PABLO ALFONSO LOPEZ CHAU NAVA                5403
CARLOS GONSALO ALVAREZ LOAYZA                4326
JORGE NIETO MONTESINOS                       4017
RAFAEL BERNARDO LÓPEZ ALIAGA CAZORLA         3536
JOSE LEON LUNA GALVEZ                        2664
RONALD DARWIN ATENCIO SOTOMAYOR              2236
ALFONSO CARLOS ESPA Y GARCES-ALVEAR          1746
MARIA SOLEDAD PEREZ TELLO                    1485
LUIS FERNANDO OLIVERA VEGA                   1472
YONHY LESCANO ANCIETA                        1372
CESAR ACUÑA PERALTA                          1298
GEORGE PATRICK FORSYTH SOMMER                1283
HERBERT CALLER GUTIERREZ                     1088
MARIO ENRIQUE VIZCARRA CORNEJO               1048
CHARLIE CARRASCO SALAZAR                      992
VLADIMIR ROY CERRON ROJAS                     945
PITTER ENRIQUE VALDERRAMA PEÑA                749
ALEX GONZALES CASTILLO                        541
PAUL DAVIS JAIMES BLANCO                      420
ROSARIO DEL PILAR FERNANDEZ BAZAN             308
MESIAS ANTONIO GUEVARA AMASIFUEN              239
ANTONIO ORTIZ VILLANO                         234
ALVARO GONZALO PAZ DE LA BARRA FREIGEIRO      223
WOLFGANG MARIO GROZO COSTA                    219
RAFAEL JORGE BELAUNDE LLOSA                   215
FRANCISCO ERNESTO DIEZ-CANSECO TÁVARA         207
ROBERTO ENRIQUE CHIABRA LEON                  197
ARMANDO JOAQUIN MASSE FERNANDEZ               168
JOSE DANIEL WILLIAMS ZAPATA                   146
FIORELLA GIANNINA MOLINELLI ARISTONDO         138
WALTER GILMER CHIRINOS PURIZAGA                80
NAPOLEON BECERRA GARCIA                        62
CARLOS ERNESTO JAICO CARRANZA                  58
Name: votos, dtype: int64

In [6]:
df_bajo = df[df["avance_pct"] < 30]

df_bajo.groupby("candidato")["votos"].sum().sort_values(ascending=False).head(5)

candidato
ROBERTO HELBERT SANCHEZ PALOMINO    33613
                                    31721
KEIKO SOFIA FUJIMORI HIGUCHI        16475
RICARDO PABLO BELMONT CASSINELLI    11481
PABLO ALFONSO LOPEZ CHAU NAVA        5403
Name: votos, dtype: int64

In [7]:
df_alto = df[df["avance_pct"] > 80]

df_alto.groupby("candidato")["votos"].sum().sort_values(ascending=False).head(5)

candidato
                                        1845903
KEIKO SOFIA FUJIMORI HIGUCHI            1789646
RAFAEL BERNARDO LÓPEZ ALIAGA CAZORLA    1565954
JORGE NIETO MONTESINOS                  1438624
RICARDO PABLO BELMONT CASSINELLI        1119108
Name: votos, dtype: int64